[2024-12-12 16:51:27,868] [INFO] [app.data.deployments:94] - Deployment inserted successfully. hospital_id=c00054, reservation_time=2024-12-12 14:30:00, version_id=1
[2024-12-12 16:52:31,260] [ERROR] [app.data.deployments:99] - (1452, 'Cannot add or update a child row: a foreign key constraint fails (`medichis_deployment`.`deployments`, CONSTRAINT `fk_version` FOREIGN KEY (`versionId`) REFERENCES `deployVersions` (`versionId`) ON DELETE CASCADE)')
[2024-12-12 17:10:28,546] [INFO] [app.data.deployments:94] - Deployment inserted successfully. hospital_id=c00054, reservation_time=2024-12-12 14:30:00, version_id=1
[2024-12-13 12:15:27,903] [ERROR] [app.service.SessionService:39] - [Errno 11001] getaddrinfo failed
[2024-12-13 12:15:28,334] [ERROR] [app.service.SessionService:39] - [Errno 11001] getaddrinfo failed
[2024-12-13 12:15:28,907] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:29,466] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:29,975] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:30,433] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:30,900] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:31,345] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:31,829] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:32,348] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:32,828] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:33,332] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:33,865] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:34,404] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:34,917] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:35,396] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:35,983] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:36,409] [ERROR] [app.service.SessionService:39] - [Errno 11001] getaddrinfo failed
[2024-12-13 12:15:36,940] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:37,433] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:38,010] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:38,573] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:40,143] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:40,763] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:41,345] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:15:41,764] [ERROR] [app.service.SessionService:39] - [Errno 11001] getaddrinfo failed
[2024-12-13 12:15:42,300] [ERROR] [app.service.SessionService:39] - 'Response' object has no attribute 'data'
[2024-12-13 12:26:48,767] [ERROR] [app.service.SessionService:41] - https://amelia2.medichis.com/internal/customer : [Errno 11001] getaddrinfo failed
[2024-12-13 12:26:49,242] [ERROR] [app.service.SessionService:41] - https://c00002.medichis.com/internal/customer : [Errno 11001] getaddrinfo failed
[2024-12-13 12:26:49,876] [ERROR] [app.service.SessionService:41] - https://c00032.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:50,428] [ERROR] [app.service.SessionService:41] - https://c00033.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:50,884] [ERROR] [app.service.SessionService:41] - https://c00034.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:51,357] [ERROR] [app.service.SessionService:41] - https://c00051.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:51,937] [ERROR] [app.service.SessionService:41] - https://c00052.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:52,423] [ERROR] [app.service.SessionService:41] - https://c00053.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:52,859] [ERROR] [app.service.SessionService:41] - https://c00054.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:53,320] [ERROR] [app.service.SessionService:41] - https://c00055.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:53,786] [ERROR] [app.service.SessionService:41] - https://c00057.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:54,357] [ERROR] [app.service.SessionService:41] - https://c00065.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:54,894] [ERROR] [app.service.SessionService:41] - https://c00066.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:55,390] [ERROR] [app.service.SessionService:41] - https://c00068.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:55,855] [ERROR] [app.service.SessionService:41] - https://c00069.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:56,368] [ERROR] [app.service.SessionService:41] - https://c00070.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:56,814] [ERROR] [app.service.SessionService:41] - https://c00071.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:57,224] [ERROR] [app.service.SessionService:41] - https://c00072.medichis.com/internal/customer : [Errno 11001] getaddrinfo failed
[2024-12-13 12:26:57,702] [ERROR] [app.service.SessionService:41] - https://c00075.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:58,137] [ERROR] [app.service.SessionService:41] - https://c00076.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:58,614] [ERROR] [app.service.SessionService:41] - https://c00077.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:59,072] [ERROR] [app.service.SessionService:41] - https://c00078.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:26:59,509] [ERROR] [app.service.SessionService:41] - https://c00079.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:27:00,056] [ERROR] [app.service.SessionService:41] - https://c00080.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:27:00,562] [ERROR] [app.service.SessionService:41] - https://c00081.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 12:27:01,049] [ERROR] [app.service.SessionService:41] - https://amelia2.medichis.com/internal/customer : [Errno 11001] getaddrinfo failed
[2024-12-13 12:27:01,607] [ERROR] [app.service.SessionService:41] - https://c00082.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:21,120] [ERROR] [app.service.SessionService:41] - https://amelia2.medichis.com/internal/customer : [Errno 11001] getaddrinfo failed
[2024-12-13 14:19:21,555] [ERROR] [app.service.SessionService:41] - https://c00002.medichis.com/internal/customer : [Errno 11001] getaddrinfo failed
[2024-12-13 14:19:22,052] [ERROR] [app.service.SessionService:41] - https://c00032.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:23,518] [ERROR] [app.service.SessionService:41] - https://c00033.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:23,980] [ERROR] [app.service.SessionService:41] - https://c00034.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:24,441] [ERROR] [app.service.SessionService:41] - https://c00051.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:24,921] [ERROR] [app.service.SessionService:41] - https://c00052.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:25,386] [ERROR] [app.service.SessionService:41] - https://c00053.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:25,875] [ERROR] [app.service.SessionService:41] - https://c00054.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:26,383] [ERROR] [app.service.SessionService:41] - https://c00055.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:26,863] [ERROR] [app.service.SessionService:41] - https://c00057.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:27,356] [ERROR] [app.service.SessionService:41] - https://c00065.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:27,852] [ERROR] [app.service.SessionService:41] - https://c00066.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:28,374] [ERROR] [app.service.SessionService:41] - https://c00068.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:28,857] [ERROR] [app.service.SessionService:41] - https://c00069.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:29,371] [ERROR] [app.service.SessionService:41] - https://c00070.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:29,854] [ERROR] [app.service.SessionService:41] - https://c00071.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:30,269] [ERROR] [app.service.SessionService:41] - https://c00072.medichis.com/internal/customer : [Errno 11001] getaddrinfo failed
[2024-12-13 14:19:30,836] [ERROR] [app.service.SessionService:41] - https://c00075.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:31,321] [ERROR] [app.service.SessionService:41] - https://c00076.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:31,795] [ERROR] [app.service.SessionService:41] - https://c00077.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:32,386] [ERROR] [app.service.SessionService:41] - https://c00078.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:32,916] [ERROR] [app.service.SessionService:41] - https://c00079.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:33,447] [ERROR] [app.service.SessionService:41] - https://c00080.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:33,976] [ERROR] [app.service.SessionService:41] - https://c00081.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:19:34,407] [ERROR] [app.service.SessionService:41] - https://amelia2.medichis.com/internal/customer : [Errno 11001] getaddrinfo failed
[2024-12-13 14:19:34,898] [ERROR] [app.service.SessionService:41] - https://c00082.medichis.com/internal/customer : 'Response' object has no attribute 'data'
[2024-12-13 14:25:16,641] [ERROR] [app.service.SessionService:43] - asyncio.tasks.gather() argument after ** must be a mapping, not list
[2024-12-13 14:30:34,644] [ERROR] [app.service.SessionService:43] - asyncio.tasks.gather() argument after ** must be a mapping, not list
[2024-12-13 14:31:01,002] [ERROR] [app.service.SessionService:43] - Request URL is missing an 'http://' or 'https://' protocol.
[2024-12-13 14:31:55,660] [ERROR] [app.service.SessionService:44] - [Errno 11001] getaddrinfo failed
[2024-12-13 15:49:48,819] [ERROR] [app.service.SessionService:44] - [Errno 11001] getaddrinfo failed
[2024-12-13 15:54:04,161] [ERROR] [app.service.SessionService:70] - Critical error: list indices must be integers or slices, not str
[2024-12-13 15:54:35,039] [ERROR] [app.service.SessionService:70] - Critical error: list indices must be integers or slices, not str
[2024-12-13 15:57:01,843] [ERROR] [app.service.SessionService:73] - Critical error: list indices must be integers or slices, not str
[2024-12-13 16:00:28,968] [ERROR] [app.service.SessionService:73] - Critical error: list indices must be integers or slices, not str
[2024-12-13 16:00:35,487] [ERROR] [app.service.SessionService:73] - Critical error: list indices must be integers or slices, not str
[2024-12-13 16:01:19,055] [ERROR] [app.service.SessionService:73] - Critical error: 'Response' object is not subscriptable
[2024-12-13 16:02:26,030] [ERROR] [app.service.SessionService:74] - Critical error: 'Response' object is not subscriptable
[2024-12-13 16:03:38,738] [ERROR] [app.service.SessionService:74] - Critical error: 'Response' object is not subscriptable
[2024-12-13 16:05:18,972] [ERROR] [app.service.SessionService:74] - Critical error: 'Response' object is not subscriptable
[2024-12-13 16:05:26,849] [ERROR] [app.service.SessionService:74] - Critical error: 'Response' object is not subscriptable
[2024-12-13 16:07:34,427] [ERROR] [app.service.SessionService:76] - Critical error: 'ConnectError' object has no attribute 'json'
[2024-12-13 16:08:11,294] [ERROR] [app.service.SessionService:76] - Critical error: 'Response' object is not subscriptable
[2024-12-13 16:09:25,305] [ERROR] [app.service.SessionService:74] - Critical error: list indices must be integers or slices, not str
[2024-12-13 16:11:36,293] [ERROR] [app.service.SessionService:74] - Critical error: list indices must be integers or slices, not str
[2024-12-13 16:12:29,504] [ERROR] [app.service.SessionService:74] - Critical error: list indices must be integers or slices, not str
[2024-12-13 17:29:38,280] [ERROR] [app.service.SessionService:104] - Critical error: gather() got an unexpected keyword argument 'headers'
[2024-12-13 17:29:41,280] [ERROR] [app.service.SessionService:104] - Critical error: gather() got an unexpected keyword argument 'headers'
[2024-12-13 17:31:32,969] [ERROR] [app.service.SessionService:104] - Critical error: gather() got an unexpected keyword argument 'headers'
[2024-12-16 15:53:13,864] [INFO] [app.data.deployVersions:60] - deployVersions inserted successfully. versionName=v1.2.3, SHA1Value=TEST
[2024-12-16 15:56:31,539] [ERROR] [app.service.DeployVersions:64] - exist versionName=v1.2.3, craetedAt=2024-12-16 15:53:11
[2024-12-16 15:57:43,140] [ERROR] [app.service.DeployVersions:64] - exist versionName=v1.2.3, craetedAt=2024-12-16 15:53:11
[2024-12-16 16:00:53,035] [INFO] [app.data.deployVersions:60] - deployVersions inserted successfully. versionName=vTEST, SHA1Value=TEST
[2024-12-16 16:00:55,492] [ERROR] [app.service.DeployVersions:64] - exist versionName=vTEST, craetedAt=2024-12-16 16:00:50
[2024-12-16 16:34:19,944] [ERROR] [app.data.deployVersions:87] - (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UPDATE deployVersions SET isNhnDeployment = 1 WHERE versionId = 1' at line 2")
[2024-12-16 17:04:57,880] [ERROR] [app.data.deployVersions:87] - (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UPDATE deployVersions SET isNhnDeployment = 1 WHERE versionId = 1' at line 2")
[2024-12-16 17:05:25,179] [ERROR] [app.data.deployVersions:87] - %d format: a real number is required, not str
[2024-12-16 17:06:05,909] [ERROR] [app.data.deployVersions:87] - %d format: a real number is required, not str
[2024-12-16 17:07:02,399] [ERROR] [app.data.deployVersions:87] - %d format: a real number is required, not str
[2024-12-16 17:07:07,430] [ERROR] [app.data.deployVersions:87] - %d format: a real number is required, not str
[2024-12-16 17:08:53,185] [ERROR] [app.data.deployVersions:87] - (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UPDATE deployVersions SET isNhnDeployment = 1 WHERE versionId = 1' at line 2")
[2024-12-16 17:09:54,062] [INFO] [app.data.deployVersions:87] - deployVersions updated successfully for versionId=1
[2024-12-16 18:56:54,951] [INFO] [app.web.deployments:85] - create_deployment : DeploymentCrete: hospitalId='string' reservationTime=datetime.datetime(2024, 12, 16, 9, 56, 53, 773000, tzinfo=TzInfo(UTC)) immediately=True versionId=0
[2024-12-16 18:56:54,952] [ERROR] [app.web.deployments:94] - Unexpected error: 'DeploymentCreate' object has no attribute 'reservation_time'
[2024-12-16 18:58:02,848] [INFO] [app.web.deployments:85] - create_deployment : DeploymentCrete: hospitalId='c00075' reservationTime=datetime.datetime(2024, 12, 16, 9, 48, 58, 32000, tzinfo=TzInfo(UTC)) immediately=True versionId=0
[2024-12-16 18:58:02,850] [ERROR] [app.web.deployments:94] - Unexpected error: 'DeploymentCreate' object has no attribute 'reservation_time'
[2024-12-16 18:58:26,839] [INFO] [app.web.deployments:85] - create_deployment : DeploymentCrete: hospitalId='c00075' reservationTime=datetime.datetime(2024, 12, 16, 9, 48, 58, 32000, tzinfo=TzInfo(UTC)) immediately=True versionId=0
[2024-12-16 18:58:26,841] [ERROR] [app.web.deployments:94] - Unexpected error: 'DeploymentCreate' object has no attribute 'reservation_time'
[2024-12-16 18:59:42,429] [INFO] [app.web.deployments:85] - create_deployment : DeploymentCrete: hospitalId='c00075' reservationTime=datetime.datetime(2024, 12, 16, 9, 48, 58, 32000, tzinfo=TzInfo(UTC)) immediately=True versionId=0
[2024-12-16 18:59:42,429] [ERROR] [app.web.deployments:94] - Unexpected error: 'DeploymentCreate' object has no attribute 'reservation_time'
[2024-12-16 18:59:48,721] [INFO] [app.web.deployments:85] - create_deployment : DeploymentCrete: hospitalId='c00075' reservationTime=datetime.datetime(2024, 12, 16, 9, 48, 58, 32000, tzinfo=TzInfo(UTC)) immediately=True versionId=0
[2024-12-16 18:59:48,721] [ERROR] [app.web.deployments:94] - Unexpected error: can't compare offset-naive and offset-aware datetimes
[2024-12-16 19:00:18,112] [INFO] [app.web.deployments:85] - create_deployment : DeploymentCrete: hospitalId='c00075' reservationTime=datetime.datetime(2024, 12, 16, 9, 48, 58) immediately=True versionId=0
[2024-12-16 19:00:18,113] [ERROR] [app.service.DeploymentService:80] - Reservation time must be in the future.
[2024-12-16 19:00:18,113] [ERROR] [app.web.deployments:91] - Validation error: Reservation time must be in the future.
[2024-12-16 19:00:28,464] [INFO] [app.web.deployments:85] - create_deployment : DeploymentCrete: hospitalId='c00075' reservationTime=datetime.datetime(2024, 12, 17, 9, 48, 58) immediately=True versionId=0
[2024-12-16 19:00:28,465] [ERROR] [app.data.deployments:101] - Database error: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`medichis_deployment`.`deployments`, CONSTRAINT `fk_version` FOREIGN KEY (`versionId`) REFERENCES `deployVersions` (`versionId`) ON DELETE CASCADE)')
[2024-12-16 19:00:28,466] [ERROR] [app.service.DeploymentService:87] - Error in reserve_deployment: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`medichis_deployment`.`deployments`, CONSTRAINT `fk_version` FOREIGN KEY (`versionId`) REFERENCES `deployVersions` (`versionId`) ON DELETE CASCADE)')
[2024-12-16 19:00:28,466] [ERROR] [app.web.deployments:94] - Unexpected error: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`medichis_deployment`.`deployments`, CONSTRAINT `fk_version` FOREIGN KEY (`versionId`) REFERENCES `deployVersions` (`versionId`) ON DELETE CASCADE)')
[2024-12-16 19:00:43,873] [INFO] [app.web.deployments:85] - create_deployment : DeploymentCrete: hospitalId='c00075' reservationTime=datetime.datetime(2024, 12, 17, 9, 48, 58) immediately=True versionId=1
[2024-12-16 19:00:43,876] [INFO] [app.data.deployments:99] - Deployment inserted successfully.
[2024-12-16 19:40:08,734] [INFO] [app.web.deployments:94] - POST: /reservation endpoint called
[2024-12-16 19:40:08,735] [INFO] [app.service.DeploymentService:87] - Starting create_deployment service method.                             Input data: hospitalId=c00075, reservationTime=2024-12-17 09:48:58, versionId=1
[2024-12-16 19:40:08,738] [INFO] [app.data.deployments:101] - Deployment inserted successfully.
[2024-12-16 19:41:30,082] [INFO] [app.web.deployments:118] - PUT: cancel_deployments: endpoint called with data: deploymentIds=[10, 11]
[2024-12-16 19:41:30,084] [ERROR] [app.web.deployments:123] - Error in cancel_deployment: 0
[2024-12-16 19:43:21,131] [INFO] [app.web.deployments:118] - PUT: cancel_deployments: endpoint called with data: deploymentIds=[10, 11]
[2024-12-16 19:43:21,133] [ERROR] [app.web.deployments:123] - Error in cancel_deployment: 0
[2024-12-16 19:44:31,596] [INFO] [app.web.deployments:118] - PUT: cancel_deployments: endpoint called with data: deploymentIds=[10, 11]
[2024-12-16 19:44:31,598] [ERROR] [app.web.deployments:123] - Error in cancel_deployment: 0
[2024-12-16 19:46:19,543] [INFO] [app.web.deployments:118] - PUT: cancel_deployments: endpoint called with data: deploymentIds=[10, 11]
[2024-12-16 19:46:19,546] [ERROR] [app.web.deployments:123] - Error in cancel_deployment: 0
[2024-12-16 19:48:19,771] [INFO] [app.web.deployments:118] - PUT: cancel_deployments: endpoint called with data: deploymentIds=[10, 11]
[2024-12-16 19:48:19,774] [ERROR] [app.web.deployments:123] - Error in cancel_deployment: 0
[2024-12-16 19:51:11,581] [INFO] [app.web.deployments:118] - PUT: cancel_deployments: endpoint called with data: deploymentIds=[10, 11]
[2024-12-16 19:51:11,583] [ERROR] [app.web.deployments:123] - Error in cancel_deployment: 0
[2024-12-16 19:52:51,840] [INFO] [app.web.deployments:118] - PUT: cancel_deployments: endpoint called with data: deploymentIds=[10, 11]
[2024-12-16 19:52:51,843] [ERROR] [app.web.deployments:123] - Error in cancel_deployment: 0
[2024-12-16 19:52:57,185] [INFO] [app.web.deployments:118] - PUT: cancel_deployments: endpoint called with data: deploymentIds=[10, 11]
[2024-12-16 19:52:57,190] [ERROR] [app.web.deployments:123] - Error in cancel_deployment: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''deploymentId': '10'},{'deploymentId': '11'})' at line 3")
[2024-12-16 19:53:41,150] [INFO] [app.web.deployments:118] - PUT: cancel_deployments: endpoint called with data: deploymentIds=[10, 11]
[2024-12-16 19:53:41,156] [ERROR] [app.web.deployments:123] - Error in cancel_deployment: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''deploymentId': '10'},{'deploymentId': '11'})' at line 3")
[2024-12-16 19:54:08,925] [INFO] [app.web.deployments:118] - PUT: cancel_deployments: endpoint called with data: deploymentIds=[10, 11]
[2024-12-16 19:54:34,312] [INFO] [app.web.deployments:118] - PUT: cancel_deployments: endpoint called with data: deploymentIds=[8, 10, 11]
